#!/usr/bin/env python3

import sys

def factorize(n):
    factors = []
    i = 2
    while i * i <= n:
        if n % i:
            i += 1
        else:
            n //= i
            factors.append(i)
    if n > 1:
        factors.append(n)
    return factors

def main():
    if len(sys.argv) != 2:
        print("Usage: {} <file>".format(sys.argv[0]))
        sys.exit(1)

    filename = sys.argv[1]

    with open(filename, 'r') as f:
        numbers = f.read().splitlines()

    for num in numbers:
        num = int(num)
        factors = factorize(num)
        print("{}={}*{}".format(num, factors[0], num // factors[0]))

if __name__ == "__main__":
    main()
